name: Bug Report
description: Report a bug or unexpected behaviour in Research Grant Craft.
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.
        Please fill in as much detail as possible so we can reproduce and fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
      placeholder: "When I click X, the app does Y instead of Z."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps to reproduce the behaviour.
      placeholder: |
        1. Open the app
        2. Navigate to ...
        3. Click on ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or error output
      description: Paste any error messages, console output, or attach screenshots.

  - type: input
    id: version
    attributes:
      label: App version or commit hash
      placeholder: "e.g. 0.1.0 or abc1234"
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome / Chromium
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I searched existing issues and this bug has not been reported before.
          required: true
        - label: I am not including sensitive proposal content in this report.
          required: true
