/**
 * mock.ts — Mock LLM adapter.
 *
 * Returns a deterministic Markdown scaffold built from the wizard state.
 * No network calls are made. Used when no API key is configured.
 */

import type { WizardState } from '@/lib/wizard/types';

export function generateMockDraft(state: WizardState): string {
  const acronym = state.acronym || 'PROJECT';
  const title = state.fullTitle || 'Untitled Project';
  const duration = state.durationMonths || 48;

  const objectiveLines = state.objectives
    .filter((o) => o.text.trim())
    .map((o, i) => `O${i + 1}: ${o.text.trim()}`)
    .join('\n');

  const partnerRows = state.partners
    .filter((p) => p.name.trim())
    .map(
      (p) =>
        `| ${p.name} | ${p.country} | ${p.type} | ${p.expertise || p.role} |`,
    )
    .join('\n');

  const milestoneLines =
    state.keyMilestones.trim() ||
    `MS1 (M6): Data Management Plan (D1.1) submitted
MS2 (M${Math.round(duration / 2)}): [Key technical milestone — go/no-go decision]
MS3 (M${duration - 4}): Pilot site validation and KPI confirmation`;

  const trlText =
    state.currentTrl && state.targetTrl
      ? `The current TRL is ${state.currentTrl}. ${acronym} targets TRL ${state.targetTrl} by Month ${duration}.`
      : 'The current Technology Readiness Level and target TRL should be stated here.';

  const gapText =
    state.stateOfArtGap.trim() ||
    '[Describe 2–4 specific limitations of existing approaches that this project addresses.]';

  const budget = state.totalBudgetEuros
    ? `€${state.totalBudgetEuros} total`
    : '[total budget to be confirmed]';

  return `# ${title} (${acronym})

> **⚠ Mock-mode draft** — This text was generated by the local mock adapter.
> Replace all placeholder sections with your own content before submitting.

---

## 1. Excellence

### 1.1 Objectives and Ambition

${acronym} has the following objectives:

${objectiveLines || 'O1: [Add your objectives in the wizard]\nO2: …\nO3: …'}

${trlText}

This project goes beyond the current state of the art by addressing: ${gapText}

### 1.2 Methodology

Our approach employs [describe your methodology here — specific methods, tools,
and frameworks]. We will use [data sources, instruments, or datasets].

We considered the following alternatives:
(a) [Alternative 1] — rejected because [reason].
(b) [Alternative 2] — rejected because [reason].

Validation criteria: [measurable success criteria — e.g. ≥85% accuracy on benchmark X].

### 1.3 Beyond the State of the Art

Current approaches have the following critical limitations:
1. ${gapText}

${acronym} advances beyond these limitations through [specific technical innovations].

---

## 2. Impact

### 2.1 Expected Outcomes and Impacts

${acronym} directly addresses the call's expected outcomes:
- Expected Outcome 1: [call outcome] → delivered via [your result]
- Expected Outcome 2: [call outcome] → delivered via [your result]

**Impact KPIs:**

| Indicator | Baseline | Target | Timeline |
|-----------|----------|--------|---------|
| [Metric 1] | [Baseline value] | [Target value] | Month ${duration - 4} |
| [Metric 2] | [Baseline value] | [Target value] | Month ${duration - 4} |
| Publications | 0 | ≥10 open access | Month ${duration} |

Beneficiaries: [list primary beneficiary groups and how each will benefit].

### 2.2 Pathway to Impact

Short-term: [specific outputs and who will use them].
IP strategy: [core components under MIT/open licence; proprietary elements protected via …].
Market entry: [commercialisation or deployment route, led by which partner].

### 2.3 Communication, Dissemination and Exploitation

Target journals: [name 2–3 relevant journals].
Conferences: [name 2–3 relevant conferences].
Open access: all peer-reviewed publications will be immediately open access.
All datasets will be deposited in Zenodo under CC BY 4.0 following FAIR principles.

### 2.4 Open Science Practices

- FAIR data: all datasets deposited in Zenodo with DOI and CC BY 4.0 licence.
- Open access: mandatory for all publications per HE Article 17 MGA.
- Open source: [specify which components are open source and under which licence].
- Data Management Plan (D1.1) will be delivered by Month 6 following the EC template.

---

## 3. Implementation

### 3.1 Work Plan and Work Packages

| WP | Title | Lead | Start | End | PM |
|----|-------|------|-------|-----|----|
| WP1 | Management | ${state.partners[0]?.name || 'Partner 1'} | M1 | M${duration} | [PM] |
| WP2 | [Research/Development] | [Lead] | M1 | M[end] | [PM] |
| WP3 | [Validation/Pilots] | [Lead] | M[start] | M[end] | [PM] |
| WP4 | Dissemination & Exploitation | [Lead] | M1 | M${duration} | [PM] |

**Milestones:**
${milestoneLines}

**Deliverables:**
- D1.1: Data Management Plan (Month 6)
- D2.1: [Technical report title] (Month [X])
- D[N].[M]: [Final report title] (Month ${duration - 2})

**Timeline:**
WP1  M1 ──────────────────────────────── M${duration}
WP2  M1 ──────────────── M[end]
WP3                M[start] ──────────── M[end]
WP4  M1 ──────────────────────────────── M${duration}
Critical path: [identify the critical path here]

### 3.2 Management Structure and Procedures

The project will be coordinated by ${state.partners[0]?.name || '[Coordinator]'}.

Governance structure:
- Project Coordinator (PC): ${state.partners[0]?.name || '[Lead partner]'}
- Steering Committee (SC): one representative per partner, quarterly meetings
- WP Leaders (WPLs): technical management of each work package

Decision-making: SC by simple majority vote; deadlock resolved by PC casting vote.
Conflict resolution: minor disputes resolved at SC level within 30 days.

**Risk register:**

| Risk | Category | Likelihood | Impact | Mitigation | Owner |
|------|----------|-----------|--------|-----------|-------|
| R1 [Technical risk] | Technical | M | H | [Mitigation measure] | [Partner] |
| R2 Partner withdrawal | Consortium | L | H | Knowledge documentation from M6 | PC |
| R3 [External risk] | External | L | M | [Mitigation measure] | [Partner] |

### 3.3 Consortium as a Whole

${
  partnerRows
    ? `| Partner | Country | Type | Key expertise |\n|---------|---------|------|---------------|\n${partnerRows}`
    : '| Partner | Country | Type | Key expertise |\n|---------|---------|------|---------------|\n| [Partner name] | [CC] | [Type] | [expertise] |'
}

Each partner brings non-duplicated expertise. Complementarity is ensured by [describe consortium assembly rationale].

### 3.4 Resources and Costs

Total budget: ${budget} across ${duration} months.

| Partner | Personnel (€) | Equipment (€) | Travel (€) | Total (€) |
|---------|--------------|--------------|-----------|----------|
| ${state.partners[0]?.name || '[Partner 1]'} | [value] | [value] | [value] | [value] |

Person-months justification: [total PM] person-months linked to WP tasks above.
Value for money: [explain why the budget is proportionate to the ambition].
`;
}
